# Generated by Django 3.0.1 on 2022-06-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_coin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_coin_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_100',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_20',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_200',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_2000',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_50',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='paid_note_500',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_coin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_coin_5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_100',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_20',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_200',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_2000',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_50',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='receive_note_500',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashledgerreport',
            name='received_amount',
            field=models.IntegerField(null=True),
        ),
    ]
